version: "3"

services:
  geth:
    image: ethereum/client-go
    ports:
      - "8501:8501"
    volumes:
      - "./.ethereum:/root/.ethereum"
      - "./config:/root/config"
      - "./scripts:/root/scripts"
    working_dir: /root
    entrypoint: sh
    command: ./scripts/run.sh
