name: Node CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  test-unit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: yarn install
        run: |
          yarn install --frozen-lockfile

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: run build
        run: |
          yarn build

      - name: run unit test
        run: |
          yarn test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  test-e2e:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: yarn install
        run: |
          yarn install --frozen-lockfile

      - name: run yarn build
        run: |
          yarn build

      - name: Geth Action
        id: geth
        uses: odanado/geth-action@v0.0.12

      - name: run e2e test
        run: |
          yarn e2e
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          RPC_URL: ${{ steps.geth.outputs.rpc_url }}
          PRIVATE_KEY: ${{ steps.geth.outputs.private_key }}

  check-esm-import:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Check ESM Import
        run: |
          yarn install
          node index.mjs
        working-directory: test/e2e/esm-import-check
