name: Node CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  test-unit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: yarn install
        run: |
          yarn install --frozen-lockfile

      - name: run build
        run: |
          yarn build

      - name: run unit test
        run: |
          yarn test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  test-e2e:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: yarn install
        run: |
          yarn install --frozen-lockfile

      - name: run yarn build
        run: |
          yarn build

      - name: Run geth for dev
        run: |
          docker-compose up -d
        working-directory: geth

      - uses: google-github-actions/auth@v0.4.3
        with:
          workload_identity_provider: ${{ secrets.GCP_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: run e2e test
        run: |
          yarn e2e
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          RPC_URL: http://localhost:8501

  check-esm-import:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Check ESM Import
        run: |
          yarn install
          node index.mjs
        working-directory: test/esm-import-check
